// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// source: simple.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Struct } from "./google/protobuf/struct";

export const protobufPackage = "simple";

/**
 * Adding a comment to the syntax will become the first
 * comment in the output source file.
 */

export interface SimpleStruct {
  simpleStruct: { [key: string]: any } | undefined;
}

function createBaseSimpleStruct(): SimpleStruct {
  return { simpleStruct: undefined };
}

export const SimpleStruct: MessageFns<SimpleStruct> = {
  encode(message: SimpleStruct, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.simpleStruct !== undefined) {
      Struct.encode(Struct.wrap(message.simpleStruct), writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SimpleStruct {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSimpleStruct();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.simpleStruct = Struct.unwrap(Struct.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SimpleStruct {
    return { simpleStruct: isObject(object.simple_struct) ? object.simple_struct : undefined };
  },

  toJSON(message: SimpleStruct, isProto?: boolean): unknown {
    const obj: any = {};
    const obj2: any = {};
    if (message.simpleStruct !== undefined) {
      obj.simple_struct = message.simpleStruct;
    }
    if (Object.hasOwn(message, "simpleStruct")) {
      obj2.simple_struct = message.simpleStruct !== undefined ? message.simpleStruct : message.simpleStruct;
    }
    return isProto ? obj2 : obj;
  },

  create<I extends Exact<DeepPartial<SimpleStruct>, I>>(base?: I): SimpleStruct {
    return SimpleStruct.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SimpleStruct>, I>>(
    object: I,
    options?: { defaultZeroFields?: string[] },
  ): SimpleStruct {
    const message = createBaseSimpleStruct();
    message.simpleStruct = object.simpleStruct ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends object ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T, isProto?: boolean): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I, options?: { defaultZeroFields?: string[] }): T;
}
