// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// source: encode.proto

/* eslint-disable */

export const protobufPackage = "";

export interface Encode {
  encode: string;
}

export const Encode: MessageFns<Encode> = {
  toJSON(message: Encode, isProto?: boolean): unknown {
    const obj: any = {};
    const obj2: any = {};
    if (message.encode !== "") {
      obj.encode = message.encode;
    }
    if (Object.hasOwn(message, "encode")) {
      obj2.encode = message.encode !== undefined ? message.encode : message.encode;
    }
    return isProto ? obj2 : obj;
  },
};

export interface MessageFns<T> {
  toJSON(message: T, isProto?: boolean): unknown;
}
