// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// source: foo.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Bar } from "./bar";

export interface Foo {
  name: string;
  bar: Bar | undefined;
}

function createBaseFoo(): Foo {
  return { name: "", bar: undefined };
}

export const Foo: MessageFns<Foo> = {
  encode(message: Foo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.bar !== undefined) {
      Bar.encode(message.bar, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Foo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFoo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.bar = Bar.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Foo {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      bar: isSet(object.bar) ? Bar.fromJSON(object.bar) : undefined,
    };
  },

  toJSON(message: Foo, isProto?: boolean): unknown {
    const obj: any = {};
    const obj2: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (Object.hasOwn(message, "name")) {
      obj2.name = message.name !== undefined ? message.name : message.name;
    }
    if (message.bar !== undefined) {
      obj.bar = Bar.toJSON(message.bar);
    }
    if (Object.hasOwn(message, "bar")) {
      obj2.bar = message.bar !== undefined ? Bar.toJSON(message.bar, true) : message.bar;
    }
    return isProto ? obj2 : obj;
  },

  create<I extends Exact<DeepPartial<Foo>, I>>(base?: I): Foo {
    return Foo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Foo>, I>>(object: I, options?: { defaultZeroFields?: string[] }): Foo {
    const message = createBaseFoo();
    message.name = object.name ?? "";
    message.bar = (object.bar !== undefined && object.bar !== null) ? Bar.fromPartial(object.bar, options) : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends object ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T, isProto?: boolean): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I, options?: { defaultZeroFields?: string[] }): T;
}
