// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// source: test.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

export interface TPartialMessage {
  field?: string | undefined;
}

export interface TPartial {
  number?: number | undefined;
  string?: string | undefined;
  map?: { [key: string]: string } | undefined;
  message?: TPartialMessage | undefined;
  repeatedMessage?: TPartialMessage[] | undefined;
  repeatedString?: string[] | undefined;
  repeatedNumber?: number[] | undefined;
}

export interface TPartial_MapEntry {
  key: string;
  value: string;
}

function createBaseTPartialMessage(): TPartialMessage {
  return {};
}

export const TPartialMessage: MessageFns<TPartialMessage> = {
  encode(message: TPartialMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.field !== undefined && message.field !== "") {
      writer.uint32(10).string(message.field);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TPartialMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTPartialMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.field = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TPartialMessage {
    return { field: isSet(object.field) ? globalThis.String(object.field) : undefined };
  },

  toJSON(message: TPartialMessage, isProto?: boolean): unknown {
    const obj: any = {};
    const obj2: any = {};
    if (message.field !== undefined && message.field !== "") {
      obj.field = message.field;
    }
    if (Object.hasOwn(message, "field")) {
      obj2.field = message.field !== undefined ? message.field : message.field;
    }
    return isProto ? obj2 : obj;
  },

  create<I extends Exact<DeepPartial<TPartialMessage>, I>>(base?: I): TPartialMessage {
    return TPartialMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TPartialMessage>, I>>(
    object: I,
    options?: { defaultZeroFields?: string[] },
  ): TPartialMessage {
    const message = createBaseTPartialMessage();
    message.field = object.field ?? undefined;
    return message;
  },
};

function createBaseTPartial(): TPartial {
  return {};
}

export const TPartial: MessageFns<TPartial> = {
  encode(message: TPartial, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.number !== undefined && message.number !== 0) {
      writer.uint32(8).int32(message.number);
    }
    if (message.string !== undefined && message.string !== "") {
      writer.uint32(18).string(message.string);
    }
    Object.entries(message.map || {}).forEach(([key, value]) => {
      TPartial_MapEntry.encode({ key: key as any, value }, writer.uint32(26).fork()).join();
    });
    if (message.message !== undefined) {
      TPartialMessage.encode(message.message, writer.uint32(34).fork()).join();
    }
    if (message.repeatedMessage !== undefined && message.repeatedMessage.length !== 0) {
      for (const v of message.repeatedMessage) {
        TPartialMessage.encode(v!, writer.uint32(42).fork()).join();
      }
    }
    if (message.repeatedString !== undefined && message.repeatedString.length !== 0) {
      for (const v of message.repeatedString) {
        writer.uint32(50).string(v!);
      }
    }
    if (message.repeatedNumber !== undefined && message.repeatedNumber.length !== 0) {
      writer.uint32(58).fork();
      for (const v of message.repeatedNumber) {
        writer.int32(v);
      }
      writer.join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TPartial {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTPartial();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.number = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.string = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          const entry3 = TPartial_MapEntry.decode(reader, reader.uint32());
          if (entry3.value !== undefined) {
            if (message.map === undefined) {
              message.map = {};
            }
            message.map![entry3.key] = entry3.value;
          }
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.message = TPartialMessage.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          if (message.repeatedMessage === undefined) {
            message.repeatedMessage = [];
          }
          const el = TPartialMessage.decode(reader, reader.uint32());
          if (el !== undefined) {
            message.repeatedMessage!?.push(el);
          }
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          if (message.repeatedString === undefined) {
            message.repeatedString = [];
          }
          const el = reader.string();
          if (el !== undefined) {
            message.repeatedString!?.push(el);
          }
          continue;
        }
        case 7: {
          if (tag === 56) {
            if (message.repeatedNumber === undefined) {
              message.repeatedNumber = [];
            }
            message.repeatedNumber!?.push(reader.int32());

            continue;
          }

          if (tag === 58) {
            if (message.repeatedNumber === undefined) {
              message.repeatedNumber = [];
            }
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.repeatedNumber!?.push(reader.int32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TPartial {
    return {
      number: isSet(object.number) ? globalThis.Number(object.number) : undefined,
      string: isSet(object.string) ? globalThis.String(object.string) : undefined,
      map: isObject(object.map)
        ? Object.entries(object.map).reduce<{ [key: string]: string }>((acc, [key, value]) => {
          acc[key] = globalThis.String(value);
          return acc;
        }, {})
        : undefined,
      message: isSet(object.message) ? TPartialMessage.fromJSON(object.message) : undefined,
      repeatedMessage: globalThis.Array.isArray(object?.repeatedMessage)
        ? object.repeatedMessage.map((e: any) => TPartialMessage.fromJSON(e))
        : undefined,
      repeatedString: globalThis.Array.isArray(object?.repeatedString)
        ? object.repeatedString.map((e: any) => globalThis.String(e))
        : undefined,
      repeatedNumber: globalThis.Array.isArray(object?.repeatedNumber)
        ? object.repeatedNumber.map((e: any) => globalThis.Number(e))
        : undefined,
    };
  },

  toJSON(message: TPartial, isProto?: boolean): unknown {
    const obj: any = {};
    const obj2: any = {};
    if (message.number !== undefined && message.number !== 0) {
      obj.number = Math.round(message.number);
    }
    if (Object.hasOwn(message, "number")) {
      obj2.number = message.number !== undefined ? Math.round(message.number) : message.number;
    }
    if (message.string !== undefined && message.string !== "") {
      obj.string = message.string;
    }
    if (Object.hasOwn(message, "string")) {
      obj2.string = message.string !== undefined ? message.string : message.string;
    }
    if (message.map) {
      const entries = Object.entries(message.map);
      if (entries.length > 0) {
        obj.map = {};
        obj2.map = {};
        entries.forEach(([k, v]) => {
          obj.map[k] = v;
          obj2.map[k] = v;
        });
      }
    }
    if (message.message !== undefined) {
      obj.message = TPartialMessage.toJSON(message.message);
    }
    if (Object.hasOwn(message, "message")) {
      obj2.message = message.message !== undefined ? TPartialMessage.toJSON(message.message, true) : message.message;
    }
    if (message.repeatedMessage?.length) {
      obj.repeatedMessage = message.repeatedMessage?.map((e) => TPartialMessage.toJSON(e));
    }
    if (message.repeatedMessage) {
      obj2.repeated_message = message.repeatedMessage?.map((e) => TPartialMessage.toJSON(e, true));
    }
    if (message.repeatedString?.length) {
      obj.repeatedString = message.repeatedString;
    }
    if (message.repeatedString) {
      obj2.repeated_string = message.repeatedString;
    }
    if (message.repeatedNumber?.length) {
      obj.repeatedNumber = message.repeatedNumber?.map((e) => Math.round(e));
    }
    if (message.repeatedNumber) {
      obj2.repeated_number = message.repeatedNumber?.map((e) => Math.round(e));
    }
    return isProto ? obj2 : obj;
  },

  create<I extends Exact<DeepPartial<TPartial>, I>>(base?: I): TPartial {
    return TPartial.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TPartial>, I>>(
    object: I,
    options?: { defaultZeroFields?: string[] },
  ): TPartial {
    const message = createBaseTPartial();
    message.number = object.number ?? (options?.defaultZeroFields?.includes("number") ? 0 : undefined);
    message.string = object.string ?? undefined;
    message.map = (object.map === undefined || object.map === null)
      ? undefined
      : Object.entries(object.map ?? {}).reduce<{ [key: string]: string }>((acc, [key, value]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      }, {});
    message.message = (object.message !== undefined && object.message !== null)
      ? TPartialMessage.fromPartial(object.message, options)
      : undefined;
    message.repeatedMessage = object.repeatedMessage?.map((e) => TPartialMessage.fromPartial(e, options)) as any;
    message.repeatedString = object.repeatedString?.map((e) => e) as any;
    message.repeatedNumber = object.repeatedNumber?.map((e) => e) as any;
    return message;
  },
};

function createBaseTPartial_MapEntry(): TPartial_MapEntry {
  return { key: "", value: "" };
}

export const TPartial_MapEntry: MessageFns<TPartial_MapEntry> = {
  encode(message: TPartial_MapEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TPartial_MapEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTPartial_MapEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TPartial_MapEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: TPartial_MapEntry, isProto?: boolean): unknown {
    const obj: any = {};
    const obj2: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (Object.hasOwn(message, "key")) {
      obj2.key = message.key !== undefined ? message.key : message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    if (Object.hasOwn(message, "value")) {
      obj2.value = message.value !== undefined ? message.value : message.value;
    }
    return isProto ? obj2 : obj;
  },

  create<I extends Exact<DeepPartial<TPartial_MapEntry>, I>>(base?: I): TPartial_MapEntry {
    return TPartial_MapEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TPartial_MapEntry>, I>>(
    object: I,
    options?: { defaultZeroFields?: string[] },
  ): TPartial_MapEntry {
    const message = createBaseTPartial_MapEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends object ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T, isProto?: boolean): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I, options?: { defaultZeroFields?: string[] }): T;
}
