// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// source: project_dto.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "./google/protobuf/timestamp";

export const protobufPackage = "";

export interface CreateMeetingRequest {
  /** 迭代Id */
  iterationId: string;
  /** 节点id */
  nodeId: string;
  /** 会议名称 */
  meetingName: string;
  /** 会议类型id */
  meetingTypeId: string;
  /** 开始时间 */
  startTime:
    | Date
    | undefined;
  /** 结束时间 */
  endTime:
    | Date
    | undefined;
  /** 会议室 */
  meetingRoomId: string[];
  /** 会议成员 */
  employeeId: string[];
  /** 工作项id */
  workItemId: string;
}

export interface FindMeetingResponse {
  items: FindMeetingItem[];
}

export interface FindMeetingItem {
  /** 迭代Id */
  iterationId: string;
  /** 节点名称 */
  nodeName: string;
  /** 会议名称 */
  meetingName: string;
  /** 会议类型id */
  meetingTypeId: string;
  /** 开始时间 */
  startTime:
    | Date
    | undefined;
  /** 结束时间 */
  endTime:
    | Date
    | undefined;
  /** 会议室 */
  meetingRoomId: string[];
  /** 会议成员 */
  employeeId: string[];
  /** 工作项id */
  workItemId: string;
  /** 会议地址 */
  meetingUrl: string;
  /** 会议录屏 */
  meetingRecord: string;
}

export interface IdRequest {
  id: string;
}

function createBaseCreateMeetingRequest(): CreateMeetingRequest {
  return {
    iterationId: "",
    nodeId: "",
    meetingName: "",
    meetingTypeId: "",
    startTime: undefined,
    endTime: undefined,
    meetingRoomId: [],
    employeeId: [],
    workItemId: "",
  };
}

export const CreateMeetingRequest: MessageFns<CreateMeetingRequest> = {
  encode(message: CreateMeetingRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    const emptyRepeatedFields: number[] = [];
    if (message.iterationId !== "") {
      writer.uint32(8).int64(message.iterationId);
    }
    if (message.nodeId !== "") {
      writer.uint32(16).int64(message.nodeId);
    }
    if (message.meetingName !== "") {
      writer.uint32(26).string(message.meetingName);
    }
    if (message.meetingTypeId !== "") {
      writer.uint32(32).int64(message.meetingTypeId);
    }
    if (message.startTime !== undefined) {
      Timestamp.encode(toTimestamp(message.startTime), writer.uint32(42).fork()).join();
    }
    if (message.endTime !== undefined) {
      Timestamp.encode(toTimestamp(message.endTime), writer.uint32(50).fork()).join();
    }
    if (message.meetingRoomId !== undefined && message.meetingRoomId.length !== 0) {
      for (const v of message.meetingRoomId) {
        writer.uint32(58).string(v!);
      }
    }
    if (message.meetingRoomId !== undefined && message.meetingRoomId.length === 0) {
      emptyRepeatedFields?.push(58);
    }
    if (message.employeeId !== undefined && message.employeeId.length !== 0) {
      writer.uint32(66).fork();
      for (const v of message.employeeId) {
        writer.int64(v);
      }
      writer.join();
    }
    if (message.employeeId !== undefined && message.employeeId.length === 0) {
      emptyRepeatedFields?.push(66);
    }
    if (message.workItemId !== "") {
      writer.uint32(72).int64(message.workItemId);
    }
    if (emptyRepeatedFields?.length !== 0) {
      const emptyUnknown = buildEmptyRepeatedToUnknown(emptyRepeatedFields);
      writer.raw(emptyUnknown);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateMeetingRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateMeetingRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.iterationId = reader.int64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.nodeId = reader.int64().toString();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.meetingName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.meetingTypeId = reader.int64().toString();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.startTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.endTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.meetingRoomId?.push(reader.string());
          continue;
        }
        case 8: {
          if (tag === 64) {
            message.employeeId?.push(reader.int64().toString());

            continue;
          }

          if (tag === 66) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.employeeId?.push(reader.int64().toString());
            }

            continue;
          }

          break;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.workItemId = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateMeetingRequest {
    return {
      iterationId: isSet(object.iterationId) ? globalThis.String(object.iterationId) : "",
      nodeId: isSet(object.nodeId) ? globalThis.String(object.nodeId) : "",
      meetingName: isSet(object.meetingName) ? globalThis.String(object.meetingName) : "",
      meetingTypeId: isSet(object.meetingTypeId) ? globalThis.String(object.meetingTypeId) : "",
      startTime: isSet(object.startTime) ? fromJsonTimestamp(object.startTime) : undefined,
      endTime: isSet(object.endTime) ? fromJsonTimestamp(object.endTime) : undefined,
      meetingRoomId: globalThis.Array.isArray(object?.meetingRoomId)
        ? object.meetingRoomId.map((e: any) => globalThis.String(e))
        : [],
      employeeId: globalThis.Array.isArray(object?.employeeId)
        ? object.employeeId.map((e: any) => globalThis.String(e))
        : [],
      workItemId: isSet(object.workItemId) ? globalThis.String(object.workItemId) : "",
    };
  },

  toJSON(message: CreateMeetingRequest): unknown {
    const obj: any = {};
    if (message.iterationId !== "") {
      obj.iterationId = message.iterationId;
    }
    if (message.nodeId !== "") {
      obj.nodeId = message.nodeId;
    }
    if (message.meetingName !== "") {
      obj.meetingName = message.meetingName;
    }
    if (message.meetingTypeId !== "") {
      obj.meetingTypeId = message.meetingTypeId;
    }
    if (message.startTime !== undefined) {
      obj.startTime = message.startTime.toISOString();
    }
    if (message.endTime !== undefined) {
      obj.endTime = message.endTime.toISOString();
    }
    if (message.meetingRoomId?.length) {
      obj.meetingRoomId = message.meetingRoomId;
    }
    if (message.employeeId?.length) {
      obj.employeeId = message.employeeId;
    }
    if (message.workItemId !== "") {
      obj.workItemId = message.workItemId;
    }
    return obj;
  },

  toRawObject(message: CreateMeetingRequest): any {
    const obj: any = {};
    if (Object.hasOwn(message, "iterationId")) {
      obj.iteration_id = message.iterationId !== undefined ? message.iterationId : message.iterationId;
    }
    if (Object.hasOwn(message, "nodeId")) {
      obj.node_id = message.nodeId !== undefined ? message.nodeId : message.nodeId;
    }
    if (Object.hasOwn(message, "meetingName")) {
      obj.meeting_name = message.meetingName !== undefined ? message.meetingName : message.meetingName;
    }
    if (Object.hasOwn(message, "meetingTypeId")) {
      obj.meeting_type_id = message.meetingTypeId !== undefined ? message.meetingTypeId : message.meetingTypeId;
    }
    if (Object.hasOwn(message, "startTime")) {
      obj.start_time = message.startTime !== undefined
        ? {
          seconds: Math.trunc(message.startTime.getTime() / 1_000),
          nanos: (message.startTime.getTime() % 1_000) * 1_000_000,
        }
        : message.startTime;
    }
    if (Object.hasOwn(message, "endTime")) {
      obj.end_time = message.endTime !== undefined
        ? {
          seconds: Math.trunc(message.endTime.getTime() / 1_000),
          nanos: (message.endTime.getTime() % 1_000) * 1_000_000,
        }
        : message.endTime;
    }
    if (message.meetingRoomId) {
      obj.meeting_room_id = message.meetingRoomId;
    }
    if (message.employeeId) {
      obj.employee_id = message.employeeId;
    }
    if (Object.hasOwn(message, "workItemId")) {
      obj.work_item_id = message.workItemId !== undefined ? message.workItemId : message.workItemId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateMeetingRequest>, I>>(base?: I): CreateMeetingRequest {
    return CreateMeetingRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateMeetingRequest>, I>>(
    object: I,
    options?: { defaultZeroFields?: string[] },
  ): CreateMeetingRequest {
    const message = createBaseCreateMeetingRequest();
    message.iterationId = object.iterationId ?? "0";
    message.nodeId = object.nodeId ?? "0";
    message.meetingName = object.meetingName ?? "";
    message.meetingTypeId = object.meetingTypeId ?? "0";
    message.startTime = object.startTime ?? undefined;
    message.endTime = object.endTime ?? undefined;
    message.meetingRoomId = object.meetingRoomId?.map((e) => e) as any;
    message.employeeId = object.employeeId?.map((e) => e) as any;
    message.workItemId = object.workItemId ?? "0";
    return message;
  },
};

function createBaseFindMeetingResponse(): FindMeetingResponse {
  return { items: [] };
}

export const FindMeetingResponse: MessageFns<FindMeetingResponse> = {
  encode(message: FindMeetingResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    const emptyRepeatedFields: number[] = [];
    if (message.items !== undefined && message.items.length !== 0) {
      for (const v of message.items) {
        FindMeetingItem.encode(v!, writer.uint32(10).fork()).join();
      }
    }
    if (message.items !== undefined && message.items.length === 0) {
      emptyRepeatedFields?.push(10);
    }
    if (emptyRepeatedFields?.length !== 0) {
      const emptyUnknown = buildEmptyRepeatedToUnknown(emptyRepeatedFields);
      writer.raw(emptyUnknown);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FindMeetingResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindMeetingResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.items?.push(FindMeetingItem.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FindMeetingResponse {
    return {
      items: globalThis.Array.isArray(object?.items) ? object.items.map((e: any) => FindMeetingItem.fromJSON(e)) : [],
    };
  },

  toJSON(message: FindMeetingResponse): unknown {
    const obj: any = {};
    if (message.items?.length) {
      obj.items = message.items?.map((e) => FindMeetingItem.toJSON(e));
    }
    return obj;
  },

  toRawObject(message: FindMeetingResponse): any {
    const obj: any = {};
    if (message.items) {
      obj.items = message.items?.map((e: any) => FindMeetingItem.toRawObject(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FindMeetingResponse>, I>>(base?: I): FindMeetingResponse {
    return FindMeetingResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FindMeetingResponse>, I>>(
    object: I,
    options?: { defaultZeroFields?: string[] },
  ): FindMeetingResponse {
    const message = createBaseFindMeetingResponse();
    message.items = object.items?.map((e) => FindMeetingItem.fromPartial(e, options)) as any;
    return message;
  },
};

function createBaseFindMeetingItem(): FindMeetingItem {
  return {
    iterationId: "",
    nodeName: "",
    meetingName: "",
    meetingTypeId: "",
    startTime: undefined,
    endTime: undefined,
    meetingRoomId: [],
    employeeId: [],
    workItemId: "",
    meetingUrl: "",
    meetingRecord: "",
  };
}

export const FindMeetingItem: MessageFns<FindMeetingItem> = {
  encode(message: FindMeetingItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    const emptyRepeatedFields: number[] = [];
    if (message.iterationId !== "") {
      writer.uint32(8).int64(message.iterationId);
    }
    if (message.nodeName !== "") {
      writer.uint32(18).string(message.nodeName);
    }
    if (message.meetingName !== "") {
      writer.uint32(26).string(message.meetingName);
    }
    if (message.meetingTypeId !== "") {
      writer.uint32(32).int64(message.meetingTypeId);
    }
    if (message.startTime !== undefined) {
      Timestamp.encode(toTimestamp(message.startTime), writer.uint32(42).fork()).join();
    }
    if (message.endTime !== undefined) {
      Timestamp.encode(toTimestamp(message.endTime), writer.uint32(50).fork()).join();
    }
    if (message.meetingRoomId !== undefined && message.meetingRoomId.length !== 0) {
      for (const v of message.meetingRoomId) {
        writer.uint32(58).string(v!);
      }
    }
    if (message.meetingRoomId !== undefined && message.meetingRoomId.length === 0) {
      emptyRepeatedFields?.push(58);
    }
    if (message.employeeId !== undefined && message.employeeId.length !== 0) {
      writer.uint32(66).fork();
      for (const v of message.employeeId) {
        writer.int64(v);
      }
      writer.join();
    }
    if (message.employeeId !== undefined && message.employeeId.length === 0) {
      emptyRepeatedFields?.push(66);
    }
    if (message.workItemId !== "") {
      writer.uint32(72).int64(message.workItemId);
    }
    if (message.meetingUrl !== "") {
      writer.uint32(90).string(message.meetingUrl);
    }
    if (message.meetingRecord !== "") {
      writer.uint32(98).string(message.meetingRecord);
    }
    if (emptyRepeatedFields?.length !== 0) {
      const emptyUnknown = buildEmptyRepeatedToUnknown(emptyRepeatedFields);
      writer.raw(emptyUnknown);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FindMeetingItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindMeetingItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.iterationId = reader.int64().toString();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.nodeName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.meetingName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.meetingTypeId = reader.int64().toString();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.startTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.endTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.meetingRoomId?.push(reader.string());
          continue;
        }
        case 8: {
          if (tag === 64) {
            message.employeeId?.push(reader.int64().toString());

            continue;
          }

          if (tag === 66) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.employeeId?.push(reader.int64().toString());
            }

            continue;
          }

          break;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.workItemId = reader.int64().toString();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.meetingUrl = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.meetingRecord = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FindMeetingItem {
    return {
      iterationId: isSet(object.iterationId) ? globalThis.String(object.iterationId) : "",
      nodeName: isSet(object.nodeName) ? globalThis.String(object.nodeName) : "",
      meetingName: isSet(object.meetingName) ? globalThis.String(object.meetingName) : "",
      meetingTypeId: isSet(object.meetingTypeId) ? globalThis.String(object.meetingTypeId) : "",
      startTime: isSet(object.startTime) ? fromJsonTimestamp(object.startTime) : undefined,
      endTime: isSet(object.endTime) ? fromJsonTimestamp(object.endTime) : undefined,
      meetingRoomId: globalThis.Array.isArray(object?.meetingRoomId)
        ? object.meetingRoomId.map((e: any) => globalThis.String(e))
        : [],
      employeeId: globalThis.Array.isArray(object?.employeeId)
        ? object.employeeId.map((e: any) => globalThis.String(e))
        : [],
      workItemId: isSet(object.workItemId) ? globalThis.String(object.workItemId) : "",
      meetingUrl: isSet(object.meetingUrl) ? globalThis.String(object.meetingUrl) : "",
      meetingRecord: isSet(object.meetingRecord) ? globalThis.String(object.meetingRecord) : "",
    };
  },

  toJSON(message: FindMeetingItem): unknown {
    const obj: any = {};
    if (message.iterationId !== "") {
      obj.iterationId = message.iterationId;
    }
    if (message.nodeName !== "") {
      obj.nodeName = message.nodeName;
    }
    if (message.meetingName !== "") {
      obj.meetingName = message.meetingName;
    }
    if (message.meetingTypeId !== "") {
      obj.meetingTypeId = message.meetingTypeId;
    }
    if (message.startTime !== undefined) {
      obj.startTime = message.startTime.toISOString();
    }
    if (message.endTime !== undefined) {
      obj.endTime = message.endTime.toISOString();
    }
    if (message.meetingRoomId?.length) {
      obj.meetingRoomId = message.meetingRoomId;
    }
    if (message.employeeId?.length) {
      obj.employeeId = message.employeeId;
    }
    if (message.workItemId !== "") {
      obj.workItemId = message.workItemId;
    }
    if (message.meetingUrl !== "") {
      obj.meetingUrl = message.meetingUrl;
    }
    if (message.meetingRecord !== "") {
      obj.meetingRecord = message.meetingRecord;
    }
    return obj;
  },

  toRawObject(message: FindMeetingItem): any {
    const obj: any = {};
    if (Object.hasOwn(message, "iterationId")) {
      obj.iteration_id = message.iterationId !== undefined ? message.iterationId : message.iterationId;
    }
    if (Object.hasOwn(message, "nodeName")) {
      obj.node_name = message.nodeName !== undefined ? message.nodeName : message.nodeName;
    }
    if (Object.hasOwn(message, "meetingName")) {
      obj.meeting_name = message.meetingName !== undefined ? message.meetingName : message.meetingName;
    }
    if (Object.hasOwn(message, "meetingTypeId")) {
      obj.meeting_type_id = message.meetingTypeId !== undefined ? message.meetingTypeId : message.meetingTypeId;
    }
    if (Object.hasOwn(message, "startTime")) {
      obj.start_time = message.startTime !== undefined
        ? {
          seconds: Math.trunc(message.startTime.getTime() / 1_000),
          nanos: (message.startTime.getTime() % 1_000) * 1_000_000,
        }
        : message.startTime;
    }
    if (Object.hasOwn(message, "endTime")) {
      obj.end_time = message.endTime !== undefined
        ? {
          seconds: Math.trunc(message.endTime.getTime() / 1_000),
          nanos: (message.endTime.getTime() % 1_000) * 1_000_000,
        }
        : message.endTime;
    }
    if (message.meetingRoomId) {
      obj.meeting_room_id = message.meetingRoomId;
    }
    if (message.employeeId) {
      obj.employee_id = message.employeeId;
    }
    if (Object.hasOwn(message, "workItemId")) {
      obj.work_item_id = message.workItemId !== undefined ? message.workItemId : message.workItemId;
    }
    if (Object.hasOwn(message, "meetingUrl")) {
      obj.meeting_url = message.meetingUrl !== undefined ? message.meetingUrl : message.meetingUrl;
    }
    if (Object.hasOwn(message, "meetingRecord")) {
      obj.meeting_record = message.meetingRecord !== undefined ? message.meetingRecord : message.meetingRecord;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FindMeetingItem>, I>>(base?: I): FindMeetingItem {
    return FindMeetingItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FindMeetingItem>, I>>(
    object: I,
    options?: { defaultZeroFields?: string[] },
  ): FindMeetingItem {
    const message = createBaseFindMeetingItem();
    message.iterationId = object.iterationId ?? "0";
    message.nodeName = object.nodeName ?? "";
    message.meetingName = object.meetingName ?? "";
    message.meetingTypeId = object.meetingTypeId ?? "0";
    message.startTime = object.startTime ?? undefined;
    message.endTime = object.endTime ?? undefined;
    message.meetingRoomId = object.meetingRoomId?.map((e) => e) as any;
    message.employeeId = object.employeeId?.map((e) => e) as any;
    message.workItemId = object.workItemId ?? "0";
    message.meetingUrl = object.meetingUrl ?? "";
    message.meetingRecord = object.meetingRecord ?? "";
    return message;
  },
};

function createBaseIdRequest(): IdRequest {
  return { id: "" };
}

export const IdRequest: MessageFns<IdRequest> = {
  encode(message: IdRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(8).int64(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IdRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIdRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): IdRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: IdRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  toRawObject(message: IdRequest): any {
    const obj: any = {};
    if (Object.hasOwn(message, "id")) {
      obj.id = message.id !== undefined ? message.id : message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<IdRequest>, I>>(base?: I): IdRequest {
    return IdRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IdRequest>, I>>(
    object: I,
    options?: { defaultZeroFields?: string[] },
  ): IdRequest {
    const message = createBaseIdRequest();
    message.id = object.id ?? "0";
    return message;
  },
};

function buildEmptyRepeatedToUnknown(emptyRepeatedFields: (number | bigint)[]): Uint8Array {
  const data: number[] = [];
  for (const fieldNum of emptyRepeatedFields) {
    appendVarint(data, fieldNum);
  }
  const result: number[] = [];
  const tag = (20000n << 3n) | 2n;
  appendVarint(result, tag);
  appendVarint(result, data.length);
  result.push(...data);
  return new Uint8Array(result);
}

function appendVarint(data: number[], value: bigint | number): number[] {
  let v = BigInt.asUintN(64, BigInt(value));
  while (v >= 0x80n) {
    data.push(Number(v & 0x7Fn) | 0x80);
    v >>= 7n;
  }
  data.push(Number(v));
  return data;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends object ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000).toString();
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (globalThis.Number(t.seconds) || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  toRawObject(message: T): any;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I, options?: { defaultZeroFields?: string[] }): T;
}
