// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// source: project_srv.proto

/* eslint-disable */
import { BinaryReader } from "@bufbuild/protobuf/wire";
import { Empty } from "./google/protobuf/empty";
import { CreateMeetingRequest, FindMeetingResponse, IdRequest } from "./project_dto";

export const protobufPackage = "sjzy_proto";

export interface Meeting {
  /** 创建会议 */
  Create(request: CreateMeetingRequest): Promise<Empty>;
  /** 查看会议 */
  Find(request: IdRequest): Promise<FindMeetingResponse>;
}

export const MeetingServiceName = "sjzy_proto.Meeting";
export class MeetingClientImpl implements Meeting {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || MeetingServiceName;
    this.rpc = rpc;
    this.Create = this.Create.bind(this);
    this.Find = this.Find.bind(this);
  }
  Create(request: CreateMeetingRequest): Promise<Empty> {
    const data = CreateMeetingRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "Create", data);
    return promise.then((data) => Empty.decode(new BinaryReader(data)));
  }

  Find(request: IdRequest): Promise<FindMeetingResponse> {
    const data = IdRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "Find", data);
    return promise.then((data) => FindMeetingResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}
