// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// source: empty-repeated.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "empty_repeated";

export enum TestEnum {
  ZERO = 0,
  ONE = 1,
  UNRECOGNIZED = -1,
}

export function testEnumFromJSON(object: any): TestEnum {
  switch (object) {
    case 0:
    case "ZERO":
      return TestEnum.ZERO;
    case 1:
    case "ONE":
      return TestEnum.ONE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TestEnum.UNRECOGNIZED;
  }
}

export function testEnumToJSON(object: TestEnum): string {
  switch (object) {
    case TestEnum.ZERO:
      return "ZERO";
    case TestEnum.ONE:
      return "ONE";
    case TestEnum.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface TestMessage {
  numbers?: number[] | undefined;
  metadata: { [key: string]: string };
  enums: TestEnum[];
  projectManager: string[];
}

export interface TestMessage_MetadataEntry {
  key: string;
  value: string;
}

function createBaseTestMessage(): TestMessage {
  return { numbers: [], metadata: {}, enums: [], projectManager: [] };
}

export const TestMessage: MessageFns<TestMessage> = {
  encode(message: TestMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    const emptyRepeatedFields: number[] = [];
    if (message.numbers !== undefined && message.numbers.length !== 0) {
      writer.uint32(10).fork();
      for (const v of message.numbers) {
        writer.int32(v);
      }
      writer.join();
    }
    if (message.numbers !== undefined && message.numbers.length === 0) {
      emptyRepeatedFields?.push(10);
    }
    Object.entries(message.metadata).forEach(([key, value]) => {
      TestMessage_MetadataEntry.encode({ key: key as any, value }, writer.uint32(18).fork()).join();
    });
    if (message.enums !== undefined && message.enums.length !== 0) {
      writer.uint32(26).fork();
      for (const v of message.enums) {
        writer.int32(v);
      }
      writer.join();
    }
    if (message.enums !== undefined && message.enums.length === 0) {
      emptyRepeatedFields?.push(26);
    }
    if (message.projectManager !== undefined && message.projectManager.length !== 0) {
      for (const v of message.projectManager) {
        writer.uint32(34).string(v!);
      }
    }
    if (message.projectManager !== undefined && message.projectManager.length === 0) {
      emptyRepeatedFields?.push(34);
    }
    if (emptyRepeatedFields?.length !== 0) {
      const emptyUnknown = buildEmptyRepeatedToUnknown(emptyRepeatedFields);
      writer.raw(emptyUnknown);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TestMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTestMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 8) {
            message.numbers?.push(reader.int32());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.numbers?.push(reader.int32());
            }

            continue;
          }

          break;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          const entry2 = TestMessage_MetadataEntry.decode(reader, reader.uint32());
          if (entry2.value !== undefined) {
            message.metadata[entry2.key] = entry2.value;
          }
          continue;
        }
        case 3: {
          if (tag === 24) {
            message.enums?.push(reader.int32() as any);

            continue;
          }

          if (tag === 26) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.enums?.push(reader.int32() as any);
            }

            continue;
          }

          break;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.projectManager?.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TestMessage {
    return {
      numbers: globalThis.Array.isArray(object?.numbers)
        ? object.numbers.map((e: any) => globalThis.Number(e))
        : undefined,
      metadata: isObject(object.metadata)
        ? Object.entries(object.metadata).reduce<{ [key: string]: string }>((acc, [key, value]) => {
          acc[key] = globalThis.String(value);
          return acc;
        }, {})
        : {},
      enums: globalThis.Array.isArray(object?.enums) ? object.enums.map((e: any) => testEnumFromJSON(e)) : [],
      projectManager: globalThis.Array.isArray(object?.projectManager)
        ? object.projectManager.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: TestMessage, isProto?: boolean): unknown {
    const obj: any = {};
    const obj2: any = {};
    if (message.numbers?.length) {
      obj.numbers = message.numbers?.map((e) => Math.round(e));
    }
    if (message.numbers) {
      obj2.numbers = message.numbers?.map((e) => Math.round(e));
    }
    if (message.metadata) {
      const entries = Object.entries(message.metadata);
      if (entries.length > 0) {
        obj.metadata = {};
        obj2.metadata = {};
        entries.forEach(([k, v]) => {
          obj.metadata[k] = v;
          obj2.metadata[k] = v;
        });
      }
    }
    if (message.enums?.length) {
      obj.enums = message.enums?.map((e) => testEnumToJSON(e));
    }
    if (message.enums) {
      obj2.enums = message.enums?.map((e) => testEnumToJSON(e));
    }
    if (message.projectManager?.length) {
      obj.projectManager = message.projectManager;
    }
    if (message.projectManager) {
      obj2.project_manager = message.projectManager;
    }
    return isProto ? obj2 : obj;
  },

  create<I extends Exact<DeepPartial<TestMessage>, I>>(base?: I): TestMessage {
    return TestMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TestMessage>, I>>(
    object: I,
    options?: { defaultZeroFields?: string[] },
  ): TestMessage {
    const message = createBaseTestMessage();
    message.numbers = object.numbers?.map((e) => e) as any;
    message.metadata = Object.entries(object.metadata ?? {}).reduce<{ [key: string]: string }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[key] = globalThis.String(value);
      }
      return acc;
    }, {});
    message.enums = object.enums?.map((e) => e) as any;
    message.projectManager = object.projectManager?.map((e) => e) as any;
    return message;
  },
};

function createBaseTestMessage_MetadataEntry(): TestMessage_MetadataEntry {
  return { key: "", value: "" };
}

export const TestMessage_MetadataEntry: MessageFns<TestMessage_MetadataEntry> = {
  encode(message: TestMessage_MetadataEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TestMessage_MetadataEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTestMessage_MetadataEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TestMessage_MetadataEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: TestMessage_MetadataEntry, isProto?: boolean): unknown {
    const obj: any = {};
    const obj2: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (Object.hasOwn(message, "key")) {
      obj2.key = message.key !== undefined ? message.key : message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    if (Object.hasOwn(message, "value")) {
      obj2.value = message.value !== undefined ? message.value : message.value;
    }
    return isProto ? obj2 : obj;
  },

  create<I extends Exact<DeepPartial<TestMessage_MetadataEntry>, I>>(base?: I): TestMessage_MetadataEntry {
    return TestMessage_MetadataEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TestMessage_MetadataEntry>, I>>(
    object: I,
    options?: { defaultZeroFields?: string[] },
  ): TestMessage_MetadataEntry {
    const message = createBaseTestMessage_MetadataEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function buildEmptyRepeatedToUnknown(emptyRepeatedFields: (number | bigint)[]): Uint8Array {
  const data: number[] = [];
  for (const fieldNum of emptyRepeatedFields) {
    appendVarint(data, fieldNum);
  }
  const result: number[] = [];
  const tag = (20000n << 3n) | 2n;
  appendVarint(result, tag);
  appendVarint(result, data.length);
  result.push(...data);
  return new Uint8Array(result);
}

function appendVarint(data: number[], value: bigint | number): number[] {
  let v = BigInt.asUintN(64, BigInt(value));
  while (v >= 0x80n) {
    data.push(Number(v & 0x7Fn) | 0x80);
    v >>= 7n;
  }
  data.push(Number(v));
  return data;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends object ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T, isProto?: boolean): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I, options?: { defaultZeroFields?: string[] }): T;
}
