// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// source: foo.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "foo";

export interface Foo {
  bar: string;
  baz: string;
}

function createBaseFoo(): Foo {
  return { bar: "", baz: "" };
}

export const Foo: MessageFns<Foo> = {
  encode(message: Foo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.bar !== "") {
      writer.uint32(10).string(message.bar);
    }
    if (message.baz !== "") {
      writer.uint32(18).string(message.baz);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Foo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFoo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.bar = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.baz = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Foo {
    return {
      bar: isSet(object.bar) ? globalThis.String(object.bar) : "",
      baz: isSet(object.baz) ? globalThis.String(object.baz) : "",
    };
  },

  toJSON(message: Foo, isProto?: boolean): unknown {
    const obj: any = {};
    const obj2: any = {};
    if (message.bar !== "") {
      obj.bar = message.bar;
    }
    if (Object.hasOwn(message, "bar")) {
      obj2.bar = message.bar !== undefined ? message.bar : message.bar;
    }
    if (message.baz !== "") {
      obj.baz = message.baz;
    }
    if (Object.hasOwn(message, "baz")) {
      obj2.baz = message.baz !== undefined ? message.baz : message.baz;
    }
    return isProto ? obj2 : obj;
  },

  create(base?: DeepPartial<Foo>): Foo {
    return Foo.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Foo>, options?: { defaultZeroFields?: string[] }): Foo {
    const message = createBaseFoo();
    message.bar = object.bar ?? "";
    message.baz = object.baz ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends object ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T, isProto?: boolean): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>, options?: { defaultZeroFields?: string[] }): T;
}
