// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// source: vector_tile.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "vector_tile";

export interface Tile {
  layers: Tile_Layer[];
}

export enum Tile_GeomType {
  UNKNOWN = 0,
  POINT = 1,
  LINESTRING = 2,
  POLYGON = 3,
  UNRECOGNIZED = -1,
}

export function tile_GeomTypeFromJSON(object: any): Tile_GeomType {
  switch (object) {
    case 0:
    case "UNKNOWN":
      return Tile_GeomType.UNKNOWN;
    case 1:
    case "POINT":
      return Tile_GeomType.POINT;
    case 2:
    case "LINESTRING":
      return Tile_GeomType.LINESTRING;
    case 3:
    case "POLYGON":
      return Tile_GeomType.POLYGON;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Tile_GeomType.UNRECOGNIZED;
  }
}

export function tile_GeomTypeToJSON(object: Tile_GeomType): string {
  switch (object) {
    case Tile_GeomType.UNKNOWN:
      return "UNKNOWN";
    case Tile_GeomType.POINT:
      return "POINT";
    case Tile_GeomType.LINESTRING:
      return "LINESTRING";
    case Tile_GeomType.POLYGON:
      return "POLYGON";
    case Tile_GeomType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Tile_Value {
  stringValue?: string | undefined;
  floatValue?: number | undefined;
  doubleValue?: number | undefined;
  intValue?: number | undefined;
  uintValue?: number | undefined;
  sintValue?: number | undefined;
  boolValue?: boolean | undefined;
}

export interface Tile_Feature {
  id?: number | undefined;
  tags: number[];
  type?: Tile_GeomType | undefined;
  geometry: number[];
}

export interface Tile_Layer {
  version: number;
  name: string;
  features: Tile_Feature[];
  keys: string[];
  values: Tile_Value[];
  extent?: number | undefined;
}

function createBaseTile(): Tile {
  return { layers: [] };
}

export const Tile: MessageFns<Tile> = {
  encode(message: Tile, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.layers !== undefined && message.layers.length !== 0) {
      for (const v of message.layers) {
        Tile_Layer.encode(v!, writer.uint32(26).fork()).join();
      }
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Tile {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTile();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.layers?.push(Tile_Layer.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Tile {
    return {
      layers: globalThis.Array.isArray(object?.layers) ? object.layers.map((e: any) => Tile_Layer.fromJSON(e)) : [],
    };
  },

  toJSON(message: Tile, isProto?: boolean): unknown {
    const obj: any = {};
    const obj2: any = {};
    if (message.layers?.length) {
      obj.layers = message.layers?.map((e) => Tile_Layer.toJSON(e));
    }
    if (message.layers) {
      obj2.layers = message.layers?.map((e) => Tile_Layer.toJSON(e, true));
    }
    return isProto ? obj2 : obj;
  },

  create<I extends Exact<DeepPartial<Tile>, I>>(base?: I): Tile {
    return Tile.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Tile>, I>>(object: I, options?: { defaultZeroFields?: string[] }): Tile {
    const message = createBaseTile();
    message.layers = object.layers?.map((e) => Tile_Layer.fromPartial(e, options)) as any;
    return message;
  },
};

function createBaseTile_Value(): Tile_Value {
  return { stringValue: "", floatValue: 0, doubleValue: 0, intValue: 0, uintValue: 0, sintValue: 0, boolValue: false };
}

export const Tile_Value: MessageFns<Tile_Value> = {
  encode(message: Tile_Value, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.stringValue !== undefined && message.stringValue !== "") {
      writer.uint32(10).string(message.stringValue);
    }
    if (message.floatValue !== undefined && message.floatValue !== 0) {
      writer.uint32(21).float(message.floatValue);
    }
    if (message.doubleValue !== undefined && message.doubleValue !== 0) {
      writer.uint32(25).double(message.doubleValue);
    }
    if (message.intValue !== undefined && message.intValue !== 0) {
      writer.uint32(32).int64(message.intValue);
    }
    if (message.uintValue !== undefined && message.uintValue !== 0) {
      writer.uint32(40).uint64(message.uintValue);
    }
    if (message.sintValue !== undefined && message.sintValue !== 0) {
      writer.uint32(48).sint64(message.sintValue);
    }
    if (message.boolValue !== undefined && message.boolValue !== false) {
      writer.uint32(56).bool(message.boolValue);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Tile_Value {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTile_Value();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.stringValue = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 21) {
            break;
          }

          message.floatValue = reader.float();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.doubleValue = reader.double();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.intValue = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.uintValue = longToNumber(reader.uint64());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.sintValue = longToNumber(reader.sint64());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.boolValue = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Tile_Value {
    return {
      stringValue: isSet(object.stringValue) ? globalThis.String(object.stringValue) : "",
      floatValue: isSet(object.floatValue) ? globalThis.Number(object.floatValue) : 0,
      doubleValue: isSet(object.doubleValue) ? globalThis.Number(object.doubleValue) : 0,
      intValue: isSet(object.intValue) ? globalThis.Number(object.intValue) : 0,
      uintValue: isSet(object.uintValue) ? globalThis.Number(object.uintValue) : 0,
      sintValue: isSet(object.sintValue) ? globalThis.Number(object.sintValue) : 0,
      boolValue: isSet(object.boolValue) ? globalThis.Boolean(object.boolValue) : false,
    };
  },

  toJSON(message: Tile_Value, isProto?: boolean): unknown {
    const obj: any = {};
    const obj2: any = {};
    if (message.stringValue !== undefined && message.stringValue !== "") {
      obj.stringValue = message.stringValue;
    }
    if (Object.hasOwn(message, "stringValue")) {
      obj2.string_value = message.stringValue !== undefined ? message.stringValue : message.stringValue;
    }
    if (message.floatValue !== undefined && message.floatValue !== 0) {
      obj.floatValue = message.floatValue;
    }
    if (Object.hasOwn(message, "floatValue")) {
      obj2.float_value = message.floatValue !== undefined ? message.floatValue : message.floatValue;
    }
    if (message.doubleValue !== undefined && message.doubleValue !== 0) {
      obj.doubleValue = message.doubleValue;
    }
    if (Object.hasOwn(message, "doubleValue")) {
      obj2.double_value = message.doubleValue !== undefined ? message.doubleValue : message.doubleValue;
    }
    if (message.intValue !== undefined && message.intValue !== 0) {
      obj.intValue = Math.round(message.intValue);
    }
    if (Object.hasOwn(message, "intValue")) {
      obj2.int_value = message.intValue !== undefined ? Math.round(message.intValue) : message.intValue;
    }
    if (message.uintValue !== undefined && message.uintValue !== 0) {
      obj.uintValue = Math.round(message.uintValue);
    }
    if (Object.hasOwn(message, "uintValue")) {
      obj2.uint_value = message.uintValue !== undefined ? Math.round(message.uintValue) : message.uintValue;
    }
    if (message.sintValue !== undefined && message.sintValue !== 0) {
      obj.sintValue = Math.round(message.sintValue);
    }
    if (Object.hasOwn(message, "sintValue")) {
      obj2.sint_value = message.sintValue !== undefined ? Math.round(message.sintValue) : message.sintValue;
    }
    if (message.boolValue !== undefined && message.boolValue !== false) {
      obj.boolValue = message.boolValue;
    }
    if (Object.hasOwn(message, "boolValue")) {
      obj2.bool_value = message.boolValue !== undefined ? message.boolValue : message.boolValue;
    }
    return isProto ? obj2 : obj;
  },

  create<I extends Exact<DeepPartial<Tile_Value>, I>>(base?: I): Tile_Value {
    return Tile_Value.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Tile_Value>, I>>(
    object: I,
    options?: { defaultZeroFields?: string[] },
  ): Tile_Value {
    const message = createBaseTile_Value();
    message.stringValue = object.stringValue ?? "";
    message.floatValue = object.floatValue ?? 0;
    message.doubleValue = object.doubleValue ?? 0;
    message.intValue = object.intValue ?? "0";
    message.uintValue = object.uintValue ?? 0;
    message.sintValue = object.sintValue ?? 0;
    message.boolValue = object.boolValue ?? false;
    return message;
  },
};

function createBaseTile_Feature(): Tile_Feature {
  return { id: 0, tags: [], type: 0, geometry: [] };
}

export const Tile_Feature: MessageFns<Tile_Feature> = {
  encode(message: Tile_Feature, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined && message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    if (message.tags !== undefined && message.tags.length !== 0) {
      writer.uint32(18).fork();
      for (const v of message.tags) {
        writer.uint32(v);
      }
      writer.join();
    }
    if (message.type !== undefined && message.type !== 0) {
      writer.uint32(24).int32(message.type);
    }
    if (message.geometry !== undefined && message.geometry.length !== 0) {
      writer.uint32(34).fork();
      for (const v of message.geometry) {
        writer.uint32(v);
      }
      writer.join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Tile_Feature {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTile_Feature();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag === 16) {
            message.tags?.push(reader.uint32());

            continue;
          }

          if (tag === 18) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.tags?.push(reader.uint32());
            }

            continue;
          }

          break;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          const _enumValue = reader.int32() as any;
          if (_enumValue !== 0) {
            message.type = _enumValue;
          }
          continue;
        }
        case 4: {
          if (tag === 32) {
            message.geometry?.push(reader.uint32());

            continue;
          }

          if (tag === 34) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.geometry?.push(reader.uint32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Tile_Feature {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      tags: globalThis.Array.isArray(object?.tags) ? object.tags.map((e: any) => globalThis.Number(e)) : [],
      type: isSet(object.type) ? tile_GeomTypeFromJSON(object.type) : 0,
      geometry: globalThis.Array.isArray(object?.geometry) ? object.geometry.map((e: any) => globalThis.Number(e)) : [],
    };
  },

  toJSON(message: Tile_Feature, isProto?: boolean): unknown {
    const obj: any = {};
    const obj2: any = {};
    if (message.id !== undefined && message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (Object.hasOwn(message, "id")) {
      obj2.id = message.id !== undefined ? Math.round(message.id) : message.id;
    }
    if (message.tags?.length) {
      obj.tags = message.tags?.map((e) => Math.round(e));
    }
    if (message.tags) {
      obj2.tags = message.tags?.map((e) => Math.round(e));
    }
    if (message.type !== undefined && message.type !== 0) {
      obj.type = tile_GeomTypeToJSON(message.type);
    }
    if (Object.hasOwn(message, "type")) {
      obj2.type = message.type !== undefined ? tile_GeomTypeToJSON(message.type) : message.type;
    }
    if (message.geometry?.length) {
      obj.geometry = message.geometry?.map((e) => Math.round(e));
    }
    if (message.geometry) {
      obj2.geometry = message.geometry?.map((e) => Math.round(e));
    }
    return isProto ? obj2 : obj;
  },

  create<I extends Exact<DeepPartial<Tile_Feature>, I>>(base?: I): Tile_Feature {
    return Tile_Feature.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Tile_Feature>, I>>(
    object: I,
    options?: { defaultZeroFields?: string[] },
  ): Tile_Feature {
    const message = createBaseTile_Feature();
    message.id = object.id ?? 0;
    message.tags = object.tags?.map((e) => e) as any;
    message.type = object.type ?? 0;
    message.geometry = object.geometry?.map((e) => e) as any;
    return message;
  },
};

function createBaseTile_Layer(): Tile_Layer {
  return { version: 1, name: "", features: [], keys: [], values: [], extent: 4096 };
}

export const Tile_Layer: MessageFns<Tile_Layer> = {
  encode(message: Tile_Layer, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.version !== 1) {
      writer.uint32(120).uint32(message.version);
    }
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.features !== undefined && message.features.length !== 0) {
      for (const v of message.features) {
        Tile_Feature.encode(v!, writer.uint32(18).fork()).join();
      }
    }
    if (message.keys !== undefined && message.keys.length !== 0) {
      for (const v of message.keys) {
        writer.uint32(26).string(v!);
      }
    }
    if (message.values !== undefined && message.values.length !== 0) {
      for (const v of message.values) {
        Tile_Value.encode(v!, writer.uint32(34).fork()).join();
      }
    }
    if (message.extent !== undefined && message.extent !== 4096) {
      writer.uint32(40).uint32(message.extent);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Tile_Layer {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTile_Layer();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.version = reader.uint32();
          continue;
        }
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.features?.push(Tile_Feature.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.keys?.push(reader.string());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.values?.push(Tile_Value.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.extent = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Tile_Layer {
    return {
      version: isSet(object.version) ? globalThis.Number(object.version) : 1,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      features: globalThis.Array.isArray(object?.features)
        ? object.features.map((e: any) => Tile_Feature.fromJSON(e))
        : [],
      keys: globalThis.Array.isArray(object?.keys) ? object.keys.map((e: any) => globalThis.String(e)) : [],
      values: globalThis.Array.isArray(object?.values) ? object.values.map((e: any) => Tile_Value.fromJSON(e)) : [],
      extent: isSet(object.extent) ? globalThis.Number(object.extent) : 4096,
    };
  },

  toJSON(message: Tile_Layer, isProto?: boolean): unknown {
    const obj: any = {};
    const obj2: any = {};
    if (message.version !== 1) {
      obj.version = Math.round(message.version);
    }
    if (Object.hasOwn(message, "version")) {
      obj2.version = message.version !== undefined ? Math.round(message.version) : message.version;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (Object.hasOwn(message, "name")) {
      obj2.name = message.name !== undefined ? message.name : message.name;
    }
    if (message.features?.length) {
      obj.features = message.features?.map((e) => Tile_Feature.toJSON(e));
    }
    if (message.features) {
      obj2.features = message.features?.map((e) => Tile_Feature.toJSON(e, true));
    }
    if (message.keys?.length) {
      obj.keys = message.keys;
    }
    if (message.keys) {
      obj2.keys = message.keys;
    }
    if (message.values?.length) {
      obj.values = message.values?.map((e) => Tile_Value.toJSON(e));
    }
    if (message.values) {
      obj2.values = message.values?.map((e) => Tile_Value.toJSON(e, true));
    }
    if (message.extent !== undefined && message.extent !== 4096) {
      obj.extent = Math.round(message.extent);
    }
    if (Object.hasOwn(message, "extent")) {
      obj2.extent = message.extent !== undefined ? Math.round(message.extent) : message.extent;
    }
    return isProto ? obj2 : obj;
  },

  create<I extends Exact<DeepPartial<Tile_Layer>, I>>(base?: I): Tile_Layer {
    return Tile_Layer.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Tile_Layer>, I>>(
    object: I,
    options?: { defaultZeroFields?: string[] },
  ): Tile_Layer {
    const message = createBaseTile_Layer();
    message.version = object.version ?? 1;
    message.name = object.name ?? "";
    message.features = object.features?.map((e) => Tile_Feature.fromPartial(e, options)) as any;
    message.keys = object.keys?.map((e) => e) as any;
    message.values = object.values?.map((e) => Tile_Value.fromPartial(e, options)) as any;
    message.extent = object.extent ?? 4096;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends object ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T, isProto?: boolean): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I, options?: { defaultZeroFields?: string[] }): T;
}
