// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// source: test-1110.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

export interface UserRule {
  /** just some fake rule for testing */
  uuid: string;
}

export interface ObjectMessage {
  namespace: string;
  name: string;
}

export interface BooleanMessage {
  namespace: string;
  name: string;
}

export interface SymbolMessage {
  namespace: string;
  name: string;
}

export interface FunctionMessage {
  namespace: string;
  name: string;
}

export interface Nested {
}

export interface Nested_Function {
  namespace: string;
  name: string;
}

function createBaseUserRule(): UserRule {
  return { uuid: "" };
}

export const UserRule: MessageFns<UserRule> = {
  encode(message: UserRule, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.uuid !== "") {
      writer.uint32(10).string(message.uuid);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserRule {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserRule();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.uuid = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserRule {
    return { uuid: isSet(object.uuid) ? globalThis.String(object.uuid) : "" };
  },

  toJSON(message: UserRule, isProto?: boolean): unknown {
    const obj: any = {};
    const obj2: any = {};
    if (message.uuid !== "") {
      obj.uuid = message.uuid;
    }
    if (Object.hasOwn(message, "uuid")) {
      obj2.UUID = message.uuid !== undefined ? message.uuid : message.uuid;
    }
    return isProto ? obj2 : obj;
  },

  create(base?: DeepPartial<UserRule>): UserRule {
    return UserRule.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UserRule>, options?: { defaultZeroFields?: string[] }): UserRule {
    const message = createBaseUserRule();
    message.uuid = object.uuid ?? "";
    return message;
  },
};

function createBaseObjectMessage(): ObjectMessage {
  return { namespace: "", name: "" };
}

export const ObjectMessage: MessageFns<ObjectMessage> = {
  encode(message: ObjectMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.namespace !== "") {
      writer.uint32(10).string(message.namespace);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ObjectMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseObjectMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.namespace = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ObjectMessage {
    return {
      namespace: isSet(object.namespace) ? globalThis.String(object.namespace) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
    };
  },

  toJSON(message: ObjectMessage, isProto?: boolean): unknown {
    const obj: any = {};
    const obj2: any = {};
    if (message.namespace !== "") {
      obj.namespace = message.namespace;
    }
    if (Object.hasOwn(message, "namespace")) {
      obj2.namespace = message.namespace !== undefined ? message.namespace : message.namespace;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (Object.hasOwn(message, "name")) {
      obj2.name = message.name !== undefined ? message.name : message.name;
    }
    return isProto ? obj2 : obj;
  },

  create(base?: DeepPartial<ObjectMessage>): ObjectMessage {
    return ObjectMessage.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ObjectMessage>, options?: { defaultZeroFields?: string[] }): ObjectMessage {
    const message = createBaseObjectMessage();
    message.namespace = object.namespace ?? "";
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseBooleanMessage(): BooleanMessage {
  return { namespace: "", name: "" };
}

export const BooleanMessage: MessageFns<BooleanMessage> = {
  encode(message: BooleanMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.namespace !== "") {
      writer.uint32(10).string(message.namespace);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BooleanMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBooleanMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.namespace = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BooleanMessage {
    return {
      namespace: isSet(object.namespace) ? globalThis.String(object.namespace) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
    };
  },

  toJSON(message: BooleanMessage, isProto?: boolean): unknown {
    const obj: any = {};
    const obj2: any = {};
    if (message.namespace !== "") {
      obj.namespace = message.namespace;
    }
    if (Object.hasOwn(message, "namespace")) {
      obj2.namespace = message.namespace !== undefined ? message.namespace : message.namespace;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (Object.hasOwn(message, "name")) {
      obj2.name = message.name !== undefined ? message.name : message.name;
    }
    return isProto ? obj2 : obj;
  },

  create(base?: DeepPartial<BooleanMessage>): BooleanMessage {
    return BooleanMessage.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<BooleanMessage>, options?: { defaultZeroFields?: string[] }): BooleanMessage {
    const message = createBaseBooleanMessage();
    message.namespace = object.namespace ?? "";
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseSymbolMessage(): SymbolMessage {
  return { namespace: "", name: "" };
}

export const SymbolMessage: MessageFns<SymbolMessage> = {
  encode(message: SymbolMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.namespace !== "") {
      writer.uint32(10).string(message.namespace);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SymbolMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSymbolMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.namespace = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SymbolMessage {
    return {
      namespace: isSet(object.namespace) ? globalThis.String(object.namespace) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
    };
  },

  toJSON(message: SymbolMessage, isProto?: boolean): unknown {
    const obj: any = {};
    const obj2: any = {};
    if (message.namespace !== "") {
      obj.namespace = message.namespace;
    }
    if (Object.hasOwn(message, "namespace")) {
      obj2.namespace = message.namespace !== undefined ? message.namespace : message.namespace;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (Object.hasOwn(message, "name")) {
      obj2.name = message.name !== undefined ? message.name : message.name;
    }
    return isProto ? obj2 : obj;
  },

  create(base?: DeepPartial<SymbolMessage>): SymbolMessage {
    return SymbolMessage.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SymbolMessage>, options?: { defaultZeroFields?: string[] }): SymbolMessage {
    const message = createBaseSymbolMessage();
    message.namespace = object.namespace ?? "";
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseFunctionMessage(): FunctionMessage {
  return { namespace: "", name: "" };
}

export const FunctionMessage: MessageFns<FunctionMessage> = {
  encode(message: FunctionMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.namespace !== "") {
      writer.uint32(10).string(message.namespace);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FunctionMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFunctionMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.namespace = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FunctionMessage {
    return {
      namespace: isSet(object.namespace) ? globalThis.String(object.namespace) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
    };
  },

  toJSON(message: FunctionMessage, isProto?: boolean): unknown {
    const obj: any = {};
    const obj2: any = {};
    if (message.namespace !== "") {
      obj.namespace = message.namespace;
    }
    if (Object.hasOwn(message, "namespace")) {
      obj2.namespace = message.namespace !== undefined ? message.namespace : message.namespace;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (Object.hasOwn(message, "name")) {
      obj2.name = message.name !== undefined ? message.name : message.name;
    }
    return isProto ? obj2 : obj;
  },

  create(base?: DeepPartial<FunctionMessage>): FunctionMessage {
    return FunctionMessage.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FunctionMessage>, options?: { defaultZeroFields?: string[] }): FunctionMessage {
    const message = createBaseFunctionMessage();
    message.namespace = object.namespace ?? "";
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseNested(): Nested {
  return {};
}

export const Nested: MessageFns<Nested> = {
  encode(_: Nested, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Nested {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNested();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): Nested {
    return {};
  },

  toJSON(_: Nested, isProto?: boolean): unknown {
    const obj: any = {};
    const obj2: any = {};
    return isProto ? obj2 : obj;
  },

  create(base?: DeepPartial<Nested>): Nested {
    return Nested.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<Nested>, options?: { defaultZeroFields?: string[] }): Nested {
    const message = createBaseNested();
    return message;
  },
};

function createBaseNested_Function(): Nested_Function {
  return { namespace: "", name: "" };
}

export const Nested_Function: MessageFns<Nested_Function> = {
  encode(message: Nested_Function, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.namespace !== "") {
      writer.uint32(10).string(message.namespace);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Nested_Function {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNested_Function();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.namespace = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Nested_Function {
    return {
      namespace: isSet(object.namespace) ? globalThis.String(object.namespace) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
    };
  },

  toJSON(message: Nested_Function, isProto?: boolean): unknown {
    const obj: any = {};
    const obj2: any = {};
    if (message.namespace !== "") {
      obj.namespace = message.namespace;
    }
    if (Object.hasOwn(message, "namespace")) {
      obj2.namespace = message.namespace !== undefined ? message.namespace : message.namespace;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (Object.hasOwn(message, "name")) {
      obj2.name = message.name !== undefined ? message.name : message.name;
    }
    return isProto ? obj2 : obj;
  },

  create(base?: DeepPartial<Nested_Function>): Nested_Function {
    return Nested_Function.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Nested_Function>, options?: { defaultZeroFields?: string[] }): Nested_Function {
    const message = createBaseNested_Function();
    message.namespace = object.namespace ?? "";
    message.name = object.name ?? "";
    return message;
  },
};

export interface APIService {
}

export const APIServiceServiceName = "APIService";
export class APIServiceClientImpl implements APIService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || APIServiceServiceName;
    this.rpc = rpc;
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends object ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T, isProto?: boolean): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>, options?: { defaultZeroFields?: string[] }): T;
}
