// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// source: global-this.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "simple";

export interface ObjectMessage {
  name: string;
}

export interface ErrorMessage {
  name: string;
}

export interface StringMessage {
  value: string;
}

export interface BooleanMessage {
  value: boolean;
}

export interface NumberMessage {
  value: number;
}

export interface ArrayMessage {
  values: StringMessage[];
}

function createBaseObjectMessage(): ObjectMessage {
  return { name: "" };
}

export const ObjectMessage: MessageFns<ObjectMessage> = {
  encode(message: ObjectMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ObjectMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseObjectMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ObjectMessage {
    return { name: isSet(object.name) ? gt.String(object.name) : "" };
  },

  toJSON(message: ObjectMessage, isProto?: boolean): unknown {
    const obj: any = {};
    const obj2: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (Object.hasOwn(message, "name")) {
      obj2.name = message.name !== undefined ? message.name : message.name;
    }
    return isProto ? obj2 : obj;
  },

  create<I extends Exact<DeepPartial<ObjectMessage>, I>>(base?: I): ObjectMessage {
    return ObjectMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ObjectMessage>, I>>(
    object: I,
    options?: { defaultZeroFields?: string[] },
  ): ObjectMessage {
    const message = createBaseObjectMessage();
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseErrorMessage(): ErrorMessage {
  return { name: "" };
}

export const ErrorMessage: MessageFns<ErrorMessage> = {
  encode(message: ErrorMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ErrorMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseErrorMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ErrorMessage {
    return { name: isSet(object.name) ? gt.String(object.name) : "" };
  },

  toJSON(message: ErrorMessage, isProto?: boolean): unknown {
    const obj: any = {};
    const obj2: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (Object.hasOwn(message, "name")) {
      obj2.name = message.name !== undefined ? message.name : message.name;
    }
    return isProto ? obj2 : obj;
  },

  create<I extends Exact<DeepPartial<ErrorMessage>, I>>(base?: I): ErrorMessage {
    return ErrorMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ErrorMessage>, I>>(
    object: I,
    options?: { defaultZeroFields?: string[] },
  ): ErrorMessage {
    const message = createBaseErrorMessage();
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseStringMessage(): StringMessage {
  return { value: "" };
}

export const StringMessage: MessageFns<StringMessage> = {
  encode(message: StringMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.value !== "") {
      writer.uint32(10).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StringMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStringMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StringMessage {
    return { value: isSet(object.value) ? gt.String(object.value) : "" };
  },

  toJSON(message: StringMessage, isProto?: boolean): unknown {
    const obj: any = {};
    const obj2: any = {};
    if (message.value !== "") {
      obj.value = message.value;
    }
    if (Object.hasOwn(message, "value")) {
      obj2.value = message.value !== undefined ? message.value : message.value;
    }
    return isProto ? obj2 : obj;
  },

  create<I extends Exact<DeepPartial<StringMessage>, I>>(base?: I): StringMessage {
    return StringMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StringMessage>, I>>(
    object: I,
    options?: { defaultZeroFields?: string[] },
  ): StringMessage {
    const message = createBaseStringMessage();
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseBooleanMessage(): BooleanMessage {
  return { value: false };
}

export const BooleanMessage: MessageFns<BooleanMessage> = {
  encode(message: BooleanMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.value !== false) {
      writer.uint32(8).bool(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BooleanMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBooleanMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.value = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BooleanMessage {
    return { value: isSet(object.value) ? gt.Boolean(object.value) : false };
  },

  toJSON(message: BooleanMessage, isProto?: boolean): unknown {
    const obj: any = {};
    const obj2: any = {};
    if (message.value !== false) {
      obj.value = message.value;
    }
    if (Object.hasOwn(message, "value")) {
      obj2.value = message.value !== undefined ? message.value : message.value;
    }
    return isProto ? obj2 : obj;
  },

  create<I extends Exact<DeepPartial<BooleanMessage>, I>>(base?: I): BooleanMessage {
    return BooleanMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BooleanMessage>, I>>(
    object: I,
    options?: { defaultZeroFields?: string[] },
  ): BooleanMessage {
    const message = createBaseBooleanMessage();
    message.value = object.value ?? false;
    return message;
  },
};

function createBaseNumberMessage(): NumberMessage {
  return { value: 0 };
}

export const NumberMessage: MessageFns<NumberMessage> = {
  encode(message: NumberMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.value !== 0) {
      writer.uint32(9).double(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NumberMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNumberMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.value = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NumberMessage {
    return { value: isSet(object.value) ? gt.Number(object.value) : 0 };
  },

  toJSON(message: NumberMessage, isProto?: boolean): unknown {
    const obj: any = {};
    const obj2: any = {};
    if (message.value !== 0) {
      obj.value = message.value;
    }
    if (Object.hasOwn(message, "value")) {
      obj2.value = message.value !== undefined ? message.value : message.value;
    }
    return isProto ? obj2 : obj;
  },

  create<I extends Exact<DeepPartial<NumberMessage>, I>>(base?: I): NumberMessage {
    return NumberMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NumberMessage>, I>>(
    object: I,
    options?: { defaultZeroFields?: string[] },
  ): NumberMessage {
    const message = createBaseNumberMessage();
    message.value = object.value ?? 0;
    return message;
  },
};

function createBaseArrayMessage(): ArrayMessage {
  return { values: [] };
}

export const ArrayMessage: MessageFns<ArrayMessage> = {
  encode(message: ArrayMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.values !== undefined && message.values.length !== 0) {
      for (const v of message.values) {
        StringMessage.encode(v!, writer.uint32(10).fork()).join();
      }
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ArrayMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseArrayMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.values?.push(StringMessage.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ArrayMessage {
    return { values: gt.Array.isArray(object?.values) ? object.values.map((e: any) => StringMessage.fromJSON(e)) : [] };
  },

  toJSON(message: ArrayMessage, isProto?: boolean): unknown {
    const obj: any = {};
    const obj2: any = {};
    if (message.values?.length) {
      obj.values = message.values?.map((e) => StringMessage.toJSON(e));
    }
    if (message.values) {
      obj2.values = message.values?.map((e) => StringMessage.toJSON(e, true));
    }
    return isProto ? obj2 : obj;
  },

  create<I extends Exact<DeepPartial<ArrayMessage>, I>>(base?: I): ArrayMessage {
    return ArrayMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ArrayMessage>, I>>(
    object: I,
    options?: { defaultZeroFields?: string[] },
  ): ArrayMessage {
    const message = createBaseArrayMessage();
    message.values = object.values?.map((e) => StringMessage.fromPartial(e, options)) as any;
    return message;
  },
};

declare const self: any | undefined;
declare const window: any | undefined;
declare const global: any | undefined;
const gt: any = (() => {
  if (typeof globalThis !== "undefined") {
    return globalThis;
  }
  if (typeof self !== "undefined") {
    return self;
  }
  if (typeof window !== "undefined") {
    return window;
  }
  if (typeof global !== "undefined") {
    return global;
  }
  throw "Unable to locate global object";
})();

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends object ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T, isProto?: boolean): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I, options?: { defaultZeroFields?: string[] }): T;
}
