// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// source: struct.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Struct } from "./google/protobuf/struct";

export const protobufPackage = "";

export interface StructMessage {
  value: { [key: string]: any } | undefined;
}

function createBaseStructMessage(): StructMessage {
  return { value: undefined };
}

export const StructMessage: MessageFns<StructMessage> = {
  encode(message: StructMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.value !== undefined) {
      Struct.encode(Struct.wrap(message.value), writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StructMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStructMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.value = Struct.unwrap(Struct.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StructMessage {
    return { value: isObject(object.value) ? object.value : undefined };
  },

  toJSON(message: StructMessage, isProto?: boolean): unknown {
    const obj: any = {};
    const obj2: any = {};
    if (message.value !== undefined) {
      obj.value = message.value;
    }
    if (Object.hasOwn(message, "value")) {
      obj2.value = message.value !== undefined ? message.value : message.value;
    }
    return isProto ? obj2 : obj;
  },

  create<I extends Exact<DeepPartial<StructMessage>, I>>(base?: I): StructMessage {
    return StructMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StructMessage>, I>>(
    object: I,
    options?: { defaultZeroFields?: string[] },
  ): StructMessage {
    const message = createBaseStructMessage();
    message.value = object.value ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends object ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T, isProto?: boolean): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I, options?: { defaultZeroFields?: string[] }): T;
}
