// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// source: google/protobuf/wrappers.proto

/* eslint-disable */

export const protobufPackage = "google.protobuf";

/**
 * Wrapper message for `double`.
 *
 * The JSON representation for `DoubleValue` is JSON number.
 *
 * Not recommended for use in new APIs, but still useful for legacy APIs and
 * has no plan to be removed.
 */
export interface DoubleValue {
  /** The double value. */
  value: number;
}

/**
 * Wrapper message for `float`.
 *
 * The JSON representation for `FloatValue` is JSON number.
 *
 * Not recommended for use in new APIs, but still useful for legacy APIs and
 * has no plan to be removed.
 */
export interface FloatValue {
  /** The float value. */
  value: number;
}

/**
 * Wrapper message for `int64`.
 *
 * The JSON representation for `Int64Value` is JSON string.
 *
 * Not recommended for use in new APIs, but still useful for legacy APIs and
 * has no plan to be removed.
 */
export interface Int64Value {
  /** The int64 value. */
  value: number;
}

/**
 * Wrapper message for `uint64`.
 *
 * The JSON representation for `UInt64Value` is JSON string.
 *
 * Not recommended for use in new APIs, but still useful for legacy APIs and
 * has no plan to be removed.
 */
export interface UInt64Value {
  /** The uint64 value. */
  value: number;
}

/**
 * Wrapper message for `int32`.
 *
 * The JSON representation for `Int32Value` is JSON number.
 *
 * Not recommended for use in new APIs, but still useful for legacy APIs and
 * has no plan to be removed.
 */
export interface Int32Value {
  /** The int32 value. */
  value?: number | undefined;
}

/**
 * Wrapper message for `uint32`.
 *
 * The JSON representation for `UInt32Value` is JSON number.
 *
 * Not recommended for use in new APIs, but still useful for legacy APIs and
 * has no plan to be removed.
 */
export interface UInt32Value {
  /** The uint32 value. */
  value: number;
}

/**
 * Wrapper message for `bool`.
 *
 * The JSON representation for `BoolValue` is JSON `true` and `false`.
 *
 * Not recommended for use in new APIs, but still useful for legacy APIs and
 * has no plan to be removed.
 */
export interface BoolValue {
  /** The bool value. */
  value: boolean;
}

/**
 * Wrapper message for `string`.
 *
 * The JSON representation for `StringValue` is JSON string.
 *
 * Not recommended for use in new APIs, but still useful for legacy APIs and
 * has no plan to be removed.
 */
export interface StringValue {
  /** The string value. */
  value: string;
}

/**
 * Wrapper message for `bytes`.
 *
 * The JSON representation for `BytesValue` is JSON string.
 *
 * Not recommended for use in new APIs, but still useful for legacy APIs and
 * has no plan to be removed.
 */
export interface BytesValue {
  /** The bytes value. */
  value: Uint8Array;
}

export const DoubleValue: MessageFns<DoubleValue> = {
  toJSON(message: DoubleValue, isProto?: boolean): unknown {
    const obj: any = {};
    const obj2: any = {};
    if (message.value !== 0) {
      obj.value = message.value;
    }
    if (Object.hasOwn(message, "value")) {
      obj2.value = message.value !== undefined ? message.value : message.value;
    }
    return isProto ? obj2 : obj;
  },
};

export const FloatValue: MessageFns<FloatValue> = {
  toJSON(message: FloatValue, isProto?: boolean): unknown {
    const obj: any = {};
    const obj2: any = {};
    if (message.value !== 0) {
      obj.value = message.value;
    }
    if (Object.hasOwn(message, "value")) {
      obj2.value = message.value !== undefined ? message.value : message.value;
    }
    return isProto ? obj2 : obj;
  },
};

export const Int64Value: MessageFns<Int64Value> = {
  toJSON(message: Int64Value, isProto?: boolean): unknown {
    const obj: any = {};
    const obj2: any = {};
    if (message.value !== 0) {
      obj.value = Math.round(message.value);
    }
    if (Object.hasOwn(message, "value")) {
      obj2.value = message.value !== undefined ? Math.round(message.value) : message.value;
    }
    return isProto ? obj2 : obj;
  },
};

export const UInt64Value: MessageFns<UInt64Value> = {
  toJSON(message: UInt64Value, isProto?: boolean): unknown {
    const obj: any = {};
    const obj2: any = {};
    if (message.value !== 0) {
      obj.value = Math.round(message.value);
    }
    if (Object.hasOwn(message, "value")) {
      obj2.value = message.value !== undefined ? Math.round(message.value) : message.value;
    }
    return isProto ? obj2 : obj;
  },
};

export const Int32Value: MessageFns<Int32Value> = {
  toJSON(message: Int32Value, isProto?: boolean): unknown {
    const obj: any = {};
    const obj2: any = {};
    if (message.value !== undefined && message.value !== 0) {
      obj.value = Math.round(message.value);
    }
    if (Object.hasOwn(message, "value")) {
      obj2.value = message.value !== undefined ? Math.round(message.value) : message.value;
    }
    return isProto ? obj2 : obj;
  },
};

export const UInt32Value: MessageFns<UInt32Value> = {
  toJSON(message: UInt32Value, isProto?: boolean): unknown {
    const obj: any = {};
    const obj2: any = {};
    if (message.value !== 0) {
      obj.value = Math.round(message.value);
    }
    if (Object.hasOwn(message, "value")) {
      obj2.value = message.value !== undefined ? Math.round(message.value) : message.value;
    }
    return isProto ? obj2 : obj;
  },
};

export const BoolValue: MessageFns<BoolValue> = {
  toJSON(message: BoolValue, isProto?: boolean): unknown {
    const obj: any = {};
    const obj2: any = {};
    if (message.value !== false) {
      obj.value = message.value;
    }
    if (Object.hasOwn(message, "value")) {
      obj2.value = message.value !== undefined ? message.value : message.value;
    }
    return isProto ? obj2 : obj;
  },
};

export const StringValue: MessageFns<StringValue> = {
  toJSON(message: StringValue, isProto?: boolean): unknown {
    const obj: any = {};
    const obj2: any = {};
    if (message.value !== "") {
      obj.value = message.value;
    }
    if (Object.hasOwn(message, "value")) {
      obj2.value = message.value !== undefined ? message.value : message.value;
    }
    return isProto ? obj2 : obj;
  },
};

export const BytesValue: MessageFns<BytesValue> = {
  toJSON(message: BytesValue, isProto?: boolean): unknown {
    const obj: any = {};
    const obj2: any = {};
    if (message.value.length !== 0) {
      obj.value = base64FromBytes(message.value);
    }
    if (Object.hasOwn(message, "value")) {
      obj2.value = message.value !== undefined ? base64FromBytes(message.value) : message.value;
    }
    return isProto ? obj2 : obj;
  },
};

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

export interface MessageFns<T> {
  toJSON(message: T, isProto?: boolean): unknown;
}
